kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dumper
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
    